### ISSUE TITLE
Image gallery populating like bullet points

### ISSUE THREAD

**Issue by danipowers** [utkwdn/utksds-plugin#30]
This is in my customized CSS to replace bullets with the chevron :
#page ul li:before {
    content: "\203a";
    color: #ff8200;
    margin-left: -0.6em;
    padding-right: 0.25em;
    font-weight: 600;
    font-size:1.5em;
}
![Screen Shot 2022-02-14 at 3 10 58 PM](https://user-images.githubusercontent.com/97196996/153938883-566f42dd-facf-4f46-a606-6c77440d77c0.png)

**Comment by spworky** [comment]
@danipowers The Gallery block utilizes unordered lists for the default structure. Instead of overriding all list elements to use the chevron pattern, I might suggest you create a custom class that you add to elements that you wish to have the chevron applied to instead. That way they are not universally added in unexpected places like the gallery. – Hope this helps! :)

**Comment by danipowers** [comment]
@spworky Yes, that makes sense. Thank you for letting me know. I can create a new class.  :)

**Comment by danipowers** [comment]
(We will have to wait and see when the bug gets fixed to allow for Advanced CSS for bullets)
